# Generated by Django 4.0.1 on 2023-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=40)),
                ('buyer_bank', models.CharField(max_length=60)),
                ('buyer_bankno', models.CharField(max_length=60)),
                ('buyer_bankname', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyprod',
            fields=[
                ('buy_date', models.DateField(primary_key=True, serialize=False)),
                ('buy_qty', models.IntegerField(max_length=10)),
                ('buy_cost', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'buyprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lprod',
            fields=[
                ('lprod_id', models.IntegerField(max_length=5)),
                ('lprod_gu', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lprod_nm', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'lprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_cost', models.IntegerField(max_length=10)),
                ('prod_price', models.IntegerField(max_length=10)),
                ('prod_sale', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
